import { render, waitFor } from "@testing-library/react-native";
import axios from "axios";

const mockData = {
  data: {
    data: [
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 4517,
        authorization_amount: 4517,
        authorization_code: "083776",
        card_token: "1822c0c9-fd91-4ce3-8ba2-8700ff801dad",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:52Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "528721965005050",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Amazon.com",
          mcc: "6065",
          state: "NY",
        },
        merchant_amount: 4517,
        merchant_authorization_amount: 4517,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 4517,
        status: "SETTLED",
        token: "f51bea64-0910-410f-94ac-0a9d14de5951",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 0,
        authorization_amount: 0,
        authorization_code: "083775",
        card_token: "1822c0c9-fd91-4ce3-8ba2-8700ff801dad",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:51Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "174030075991",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Amazon.com",
          mcc: "5009",
          state: "NY",
        },
        merchant_amount: 0,
        merchant_authorization_amount: 0,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 0,
        status: "EXPIRED",
        token: "6b8bda64-c160-4e0c-ad06-b68ab016c935",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 9297,
        authorization_amount: 9297,
        authorization_code: "083774",
        card_token: "3d5638eb-a60c-4b1d-84de-f7b7b2081dde",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:50Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "703672731031654",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Home Depot",
          mcc: "1707",
          state: "NY",
        },
        merchant_amount: 9297,
        merchant_authorization_amount: 9297,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 9297,
        status: "SETTLED",
        token: "a8f22a2f-3673-427d-a72a-77d97cd9eb2a",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 0,
        authorization_amount: 0,
        authorization_code: "083773",
        card_token: "3d5638eb-a60c-4b1d-84de-f7b7b2081dde",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:48Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "174030075991",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Home Depot",
          mcc: "2256",
          state: "NY",
        },
        merchant_amount: 0,
        merchant_authorization_amount: 0,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 0,
        status: "EXPIRED",
        token: "bff986f5-a52e-45c6-90c4-de2410e7289c",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 8142,
        authorization_amount: 8142,
        authorization_code: "083772",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:47Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "270020890368374",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "9146",
          state: "NY",
        },
        merchant_amount: 8142,
        merchant_authorization_amount: 8142,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 8142,
        status: "SETTLED",
        token: "ecedf221-fbaa-4e8f-97c1-98ff7ec6cb4d",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 7557,
        authorization_amount: 7557,
        authorization_code: "083771",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:46Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "748634754256547",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "6678",
          state: "NY",
        },
        merchant_amount: 7557,
        merchant_authorization_amount: 7557,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 7557,
        status: "SETTLED",
        token: "024b5752-7b54-4d20-ab70-406235e0db0f",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 7771,
        authorization_amount: 7771,
        authorization_code: "083770",
        card_token: "1822c0c9-fd91-4ce3-8ba2-8700ff801dad",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:44Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "456325793392198",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Amazon.com",
          mcc: "9539",
          state: "NY",
        },
        merchant_amount: 7771,
        merchant_authorization_amount: 7771,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 7771,
        status: "SETTLED",
        token: "10491a89-100e-40cb-ba59-c3323c5aa173",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 3476,
        authorization_amount: 3476,
        authorization_code: "083769",
        card_token: "3d5638eb-a60c-4b1d-84de-f7b7b2081dde",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:43Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "614815332293009",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Home Depot",
          mcc: "1767",
          state: "NY",
        },
        merchant_amount: 3476,
        merchant_authorization_amount: 3476,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 3476,
        status: "SETTLED",
        token: "5a479761-f6df-453c-8020-83db7d534d81",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 1936,
        authorization_amount: 1936,
        authorization_code: "083768",
        card_token: "e687e744-aa1c-4f1a-b4f1-4783d234c1f0",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:41Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "661223589288390",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Daiso",
          mcc: "3400",
          state: "NY",
        },
        merchant_amount: 1936,
        merchant_authorization_amount: 1936,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 1936,
        status: "SETTLED",
        token: "75f96686-096f-41eb-ac30-f5ed2b6fc5c1",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 2601,
        authorization_amount: 2601,
        authorization_code: "083767",
        card_token: "117686ca-fb58-47b5-9ed8-0b460b92c58d",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:40Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "863317509061997",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Walmart",
          mcc: "4949",
          state: "NY",
        },
        merchant_amount: 2601,
        merchant_authorization_amount: 2601,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 2601,
        status: "SETTLED",
        token: "90e05160-c176-46ae-b5dc-6e4a07e5ae44",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 1709,
        authorization_amount: 1709,
        authorization_code: "083766",
        card_token: "117686ca-fb58-47b5-9ed8-0b460b92c58d",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:38Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "463554912882533",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Walmart",
          mcc: "7651",
          state: "NY",
        },
        merchant_amount: 1709,
        merchant_authorization_amount: 1709,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 1709,
        status: "SETTLED",
        token: "e157b600-72ad-4812-a868-a16d09660cdd",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 4654,
        authorization_amount: 4654,
        authorization_code: "083765",
        card_token: "e687e744-aa1c-4f1a-b4f1-4783d234c1f0",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:37Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "533470285959333",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Daiso",
          mcc: "7565",
          state: "NY",
        },
        merchant_amount: 4654,
        merchant_authorization_amount: 4654,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 4654,
        status: "SETTLED",
        token: "56557f28-9220-4a2e-b361-e9f54a686bac",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 4289,
        authorization_amount: 4289,
        authorization_code: "083764",
        card_token: "3d5638eb-a60c-4b1d-84de-f7b7b2081dde",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:36Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "341804361059546",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Home Depot",
          mcc: "6766",
          state: "NY",
        },
        merchant_amount: 4289,
        merchant_authorization_amount: 4289,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 4289,
        status: "SETTLED",
        token: "e2ffe845-f55a-4c1c-96e3-27082ecf8272",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 8868,
        authorization_amount: 8868,
        authorization_code: "083763",
        card_token: "1822c0c9-fd91-4ce3-8ba2-8700ff801dad",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:35Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "680183926906468",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Amazon.com",
          mcc: "5168",
          state: "NY",
        },
        merchant_amount: 8868,
        merchant_authorization_amount: 8868,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 8868,
        status: "SETTLED",
        token: "5286029e-0c71-4a8e-8755-fdc310dc0d72",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 600,
        authorization_amount: 600,
        authorization_code: "083762",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:33Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "651582945759823",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "6344",
          state: "NY",
        },
        merchant_amount: 600,
        merchant_authorization_amount: 600,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 600,
        status: "SETTLED",
        token: "e4cfa1e3-436a-451c-b23e-b81cf0b5925f",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 0,
        authorization_amount: 0,
        authorization_code: "083761",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:32Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "174030075991",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "6915",
          state: "NY",
        },
        merchant_amount: 0,
        merchant_authorization_amount: 0,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 0,
        status: "EXPIRED",
        token: "02d82a5b-a0a5-4aa1-82d0-aa0ccba60944",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 8773,
        authorization_amount: 8773,
        authorization_code: "083760",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:30Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "139616771780685",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "6330",
          state: "NY",
        },
        merchant_amount: 8773,
        merchant_authorization_amount: 8773,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 8773,
        status: "SETTLED",
        token: "b888ddb1-8b47-4d8d-91be-dfaa3ad28076",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 9605,
        authorization_amount: 9605,
        authorization_code: "083759",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:28Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "142951559325410",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "5054",
          state: "NY",
        },
        merchant_amount: 9605,
        merchant_authorization_amount: 9605,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 9605,
        status: "SETTLED",
        token: "47fdf401-6aa3-4c78-8076-13e8d32afb8e",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 5575,
        authorization_amount: 5575,
        authorization_code: "083758",
        card_token: "117686ca-fb58-47b5-9ed8-0b460b92c58d",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:27Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "491768459165913",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Walmart",
          mcc: "8332",
          state: "NY",
        },
        merchant_amount: 5575,
        merchant_authorization_amount: 5575,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 5575,
        status: "SETTLED",
        token: "cd3f5d0b-28c6-4768-86ec-e427b48b0e79",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 5267,
        authorization_amount: 5267,
        authorization_code: "083757",
        card_token: "1822c0c9-fd91-4ce3-8ba2-8700ff801dad",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:25Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "757911108826279",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Amazon.com",
          mcc: "9939",
          state: "NY",
        },
        merchant_amount: 5267,
        merchant_authorization_amount: 5267,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 5267,
        status: "SETTLED",
        token: "991040f6-02ee-406c-9d18-d66f1a16782f",
      },
    ],
    total_pages: 5,
  },
};
describe("Example", () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
    axios.get.mockClear();

    // Mock the axios.get function to return the mockData
    axios.get.mockResolvedValue(mockData);
  });

  it("should have sign up text", async () => {
    await expect(element(by.id("sign-up-text"))).toBeVisible();
  });

  it("should find signup inputs", async () => {
    await expect(element(by.id("signup-email-input"))).toBeVisible();
    await expect(element(by.id("signup-password-input"))).toBeVisible();
  });

  it("should log in", async () => {
    await element(by.id("switch")).tap();
    await element(by.id("signup-email-input")).typeText("example@gmail.com");
    await element(by.id("signup-password-input")).typeText("password");
    await element(by.id("submit")).tap();
  });

  it("should scroll flatlist", async () => {
    await waitFor(element(by.id("flatlist"))).toBeVisible();

    await waitFor(element(by.id("item_1822c0c9-fd91-4ce3-8ba2-8700ff801dad")))
      .toBeVisible()
      .whileElement(by.id("flatlist"))
      .swipe("up", "fast", 0.8);
  });
});
