console.log("We are now using our mocked data");

const mockData = {
  data: {
    data: [
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 4517,
        authorization_amount: 4517,
        authorization_code: "083776",
        card_token: "1822c0c9-fd91-4ce3-8ba2-8700ff801dad",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:52Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "528721965005050",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Amazon.com",
          mcc: "6065",
          state: "NY",
        },
        merchant_amount: 4517,
        merchant_authorization_amount: 4517,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 4517,
        status: "SETTLED",
        token: "f51bea64-0910-410f-94ac-0a9d14de5951",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 0,
        authorization_amount: 0,
        authorization_code: "083775",
        card_token: "1822c0c9-fd91-4ce3-8ba2-8700ff801dad",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:51Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "174030075991",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Amazon.com",
          mcc: "5009",
          state: "NY",
        },
        merchant_amount: 0,
        merchant_authorization_amount: 0,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 0,
        status: "EXPIRED",
        token: "6b8bda64-c160-4e0c-ad06-b68ab016c935",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 9297,
        authorization_amount: 9297,
        authorization_code: "083774",
        card_token: "3d5638eb-a60c-4b1d-84de-f7b7b2081dde",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:50Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "703672731031654",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Home Depot",
          mcc: "1707",
          state: "NY",
        },
        merchant_amount: 9297,
        merchant_authorization_amount: 9297,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 9297,
        status: "SETTLED",
        token: "a8f22a2f-3673-427d-a72a-77d97cd9eb2a",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 0,
        authorization_amount: 0,
        authorization_code: "083773",
        card_token: "3d5638eb-a60c-4b1d-84de-f7b7b2081dde",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:48Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "174030075991",
          city: "NEW YORK",
          country: "USA",
          descriptor: "Home Depot",
          mcc: "2256",
          state: "NY",
        },
        merchant_amount: 0,
        merchant_authorization_amount: 0,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 0,
        status: "EXPIRED",
        token: "bff986f5-a52e-45c6-90c4-de2410e7289c",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 8142,
        authorization_amount: 8142,
        authorization_code: "083772",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:47Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "270020890368374",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "9146",
          state: "NY",
        },
        merchant_amount: 8142,
        merchant_authorization_amount: 8142,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 8142,
        status: "SETTLED",
        token: "ecedf221-fbaa-4e8f-97c1-98ff7ec6cb4d",
      },
      {
        acquirer_fee: 0,
        acquirer_reference_number: null,
        amount: 7557,
        authorization_amount: 7557,
        authorization_code: "083771",
        card_token: "f8f1954e-9411-438e-b4c6-853d38b58003",
        cardholder_authentication: {
          "3ds_version": "2",
          acquirer_exemption: "NONE",
          liability_shift: "3DS_AUTHENTICATED",
          verification_attempted: "NONE",
          verification_result: "FRICTIONLESS",
        },
        created: "2023-05-15T06:42:46Z",
        events: [[Object], [Object]],
        merchant: {
          acceptor_id: "748634754256547",
          city: "NEW YORK",
          country: "USA",
          descriptor: "REI",
          mcc: "6678",
          state: "NY",
        },
        merchant_amount: 7557,
        merchant_authorization_amount: 7557,
        merchant_currency: "USD",
        network: "VISA",
        result: "APPROVED",
        settled_amount: 7557,
        status: "SETTLED",
        token: "024b5752-7b54-4d20-ab70-406235e0db0f",
      },
    ],
    total_pages: 5,
  },
};

export const getLithicData = async () => {
  console.log("Mock data");
  return mockData.data;
};
